template: testify

packages:
  portal-system/internal/repository:
    config:
      dir: internal/repository/mocks
      pkgname: mocks
      filename: "{{.InterfaceName | snakecase}}.go"
      structname: "{{.InterfaceName}}"
      all: true

  portal-system/internal/service:
    config:
      dir: internal/service/mocks
      pkgname: mocks
      filename: "{{.InterfaceName | snakecase}}.go"
      structname: "{{.InterfaceName}}"
      all: true