template: testify

packages:
  portal-system/internal/repositories:
    config:
      dir: internal/repositories/mocks
      pkgname: mocks
      filename: "{{.InterfaceName | snakecase}}.go"
      structname: "{{.InterfaceName}}"
      all: true

  portal-system/internal/services:
    config:
      dir: internal/services/mocks
      pkgname: mocks
      filename: "{{.InterfaceName | snakecase}}.go"
      structname: "{{.InterfaceName}}"
      all: true