// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"portal-system/shared/events/notification/v1"

	mock "github.com/stretchr/testify/mock"
)

// NewNotificationPublisher creates a new instance of NotificationPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationPublisher {
	mock := &NotificationPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NotificationPublisher is an autogenerated mock type for the NotificationPublisher type
type NotificationPublisher struct {
	mock.Mock
}

type NotificationPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationPublisher) EXPECT() *NotificationPublisher_Expecter {
	return &NotificationPublisher_Expecter{mock: &_m.Mock}
}

// PublishNotificationRequested provides a mock function for the type NotificationPublisher
func (_mock *NotificationPublisher) PublishNotificationRequested(ctx context.Context, event v1.NotificationRequestedEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishNotificationRequested")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1.NotificationRequestedEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NotificationPublisher_PublishNotificationRequested_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishNotificationRequested'
type NotificationPublisher_PublishNotificationRequested_Call struct {
	*mock.Call
}

// PublishNotificationRequested is a helper method to define mock.On call
//   - ctx context.Context
//   - event v1.NotificationRequestedEvent
func (_e *NotificationPublisher_Expecter) PublishNotificationRequested(ctx interface{}, event interface{}) *NotificationPublisher_PublishNotificationRequested_Call {
	return &NotificationPublisher_PublishNotificationRequested_Call{Call: _e.mock.On("PublishNotificationRequested", ctx, event)}
}

func (_c *NotificationPublisher_PublishNotificationRequested_Call) Run(run func(ctx context.Context, event v1.NotificationRequestedEvent)) *NotificationPublisher_PublishNotificationRequested_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v1.NotificationRequestedEvent
		if args[1] != nil {
			arg1 = args[1].(v1.NotificationRequestedEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationPublisher_PublishNotificationRequested_Call) Return(err error) *NotificationPublisher_PublishNotificationRequested_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NotificationPublisher_PublishNotificationRequested_Call) RunAndReturn(run func(ctx context.Context, event v1.NotificationRequestedEvent) error) *NotificationPublisher_PublishNotificationRequested_Call {
	_c.Call.Return(run)
	return _c
}
