// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"portal-system/internal/model"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewOutboxRepository creates a new instance of OutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OutboxRepository {
	mock := &OutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OutboxRepository is an autogenerated mock type for the OutboxRepository type
type OutboxRepository struct {
	mock.Mock
}

type OutboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OutboxRepository) EXPECT() *OutboxRepository_Expecter {
	return &OutboxRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type OutboxRepository
func (_mock *OutboxRepository) Create(ctx context.Context, event *model.OutboxEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.OutboxEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OutboxRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OutboxRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - event *model.OutboxEvent
func (_e *OutboxRepository_Expecter) Create(ctx interface{}, event interface{}) *OutboxRepository_Create_Call {
	return &OutboxRepository_Create_Call{Call: _e.mock.On("Create", ctx, event)}
}

func (_c *OutboxRepository_Create_Call) Run(run func(ctx context.Context, event *model.OutboxEvent)) *OutboxRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.OutboxEvent
		if args[1] != nil {
			arg1 = args[1].(*model.OutboxEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OutboxRepository_Create_Call) Return(err error) *OutboxRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OutboxRepository_Create_Call) RunAndReturn(run func(ctx context.Context, event *model.OutboxEvent) error) *OutboxRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingForUpdate provides a mock function for the type OutboxRepository
func (_mock *OutboxRepository) ListPendingForUpdate(ctx context.Context, limit int) ([]model.OutboxEvent, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingForUpdate")
	}

	var r0 []model.OutboxEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]model.OutboxEvent, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []model.OutboxEvent); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OutboxEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OutboxRepository_ListPendingForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingForUpdate'
type OutboxRepository_ListPendingForUpdate_Call struct {
	*mock.Call
}

// ListPendingForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *OutboxRepository_Expecter) ListPendingForUpdate(ctx interface{}, limit interface{}) *OutboxRepository_ListPendingForUpdate_Call {
	return &OutboxRepository_ListPendingForUpdate_Call{Call: _e.mock.On("ListPendingForUpdate", ctx, limit)}
}

func (_c *OutboxRepository_ListPendingForUpdate_Call) Run(run func(ctx context.Context, limit int)) *OutboxRepository_ListPendingForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OutboxRepository_ListPendingForUpdate_Call) Return(outboxEvents []model.OutboxEvent, err error) *OutboxRepository_ListPendingForUpdate_Call {
	_c.Call.Return(outboxEvents, err)
	return _c
}

func (_c *OutboxRepository_ListPendingForUpdate_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]model.OutboxEvent, error)) *OutboxRepository_ListPendingForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// MarkDeadLetter provides a mock function for the type OutboxRepository
func (_mock *OutboxRepository) MarkDeadLetter(ctx context.Context, id uuid.UUID, lastError string) error {
	ret := _mock.Called(ctx, id, lastError)

	if len(ret) == 0 {
		panic("no return value specified for MarkDeadLetter")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, lastError)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OutboxRepository_MarkDeadLetter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDeadLetter'
type OutboxRepository_MarkDeadLetter_Call struct {
	*mock.Call
}

// MarkDeadLetter is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - lastError string
func (_e *OutboxRepository_Expecter) MarkDeadLetter(ctx interface{}, id interface{}, lastError interface{}) *OutboxRepository_MarkDeadLetter_Call {
	return &OutboxRepository_MarkDeadLetter_Call{Call: _e.mock.On("MarkDeadLetter", ctx, id, lastError)}
}

func (_c *OutboxRepository_MarkDeadLetter_Call) Run(run func(ctx context.Context, id uuid.UUID, lastError string)) *OutboxRepository_MarkDeadLetter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OutboxRepository_MarkDeadLetter_Call) Return(err error) *OutboxRepository_MarkDeadLetter_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OutboxRepository_MarkDeadLetter_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, lastError string) error) *OutboxRepository_MarkDeadLetter_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPublished provides a mock function for the type OutboxRepository
func (_mock *OutboxRepository) MarkPublished(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkPublished")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OutboxRepository_MarkPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPublished'
type OutboxRepository_MarkPublished_Call struct {
	*mock.Call
}

// MarkPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *OutboxRepository_Expecter) MarkPublished(ctx interface{}, id interface{}) *OutboxRepository_MarkPublished_Call {
	return &OutboxRepository_MarkPublished_Call{Call: _e.mock.On("MarkPublished", ctx, id)}
}

func (_c *OutboxRepository_MarkPublished_Call) Run(run func(ctx context.Context, id uuid.UUID)) *OutboxRepository_MarkPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OutboxRepository_MarkPublished_Call) Return(err error) *OutboxRepository_MarkPublished_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OutboxRepository_MarkPublished_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *OutboxRepository_MarkPublished_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPublishing provides a mock function for the type OutboxRepository
func (_mock *OutboxRepository) MarkPublishing(ctx context.Context, ids []uuid.UUID, workerID string) error {
	ret := _mock.Called(ctx, ids, workerID)

	if len(ret) == 0 {
		panic("no return value specified for MarkPublishing")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, ids, workerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OutboxRepository_MarkPublishing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPublishing'
type OutboxRepository_MarkPublishing_Call struct {
	*mock.Call
}

// MarkPublishing is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
//   - workerID string
func (_e *OutboxRepository_Expecter) MarkPublishing(ctx interface{}, ids interface{}, workerID interface{}) *OutboxRepository_MarkPublishing_Call {
	return &OutboxRepository_MarkPublishing_Call{Call: _e.mock.On("MarkPublishing", ctx, ids, workerID)}
}

func (_c *OutboxRepository_MarkPublishing_Call) Run(run func(ctx context.Context, ids []uuid.UUID, workerID string)) *OutboxRepository_MarkPublishing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OutboxRepository_MarkPublishing_Call) Return(err error) *OutboxRepository_MarkPublishing_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OutboxRepository_MarkPublishing_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID, workerID string) error) *OutboxRepository_MarkPublishing_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRetryScheduled provides a mock function for the type OutboxRepository
func (_mock *OutboxRepository) MarkRetryScheduled(ctx context.Context, id uuid.UUID, retryCount int, lastError string, nextRetryAt time.Time) error {
	ret := _mock.Called(ctx, id, retryCount, lastError, nextRetryAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkRetryScheduled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, string, time.Time) error); ok {
		r0 = returnFunc(ctx, id, retryCount, lastError, nextRetryAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OutboxRepository_MarkRetryScheduled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRetryScheduled'
type OutboxRepository_MarkRetryScheduled_Call struct {
	*mock.Call
}

// MarkRetryScheduled is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - retryCount int
//   - lastError string
//   - nextRetryAt time.Time
func (_e *OutboxRepository_Expecter) MarkRetryScheduled(ctx interface{}, id interface{}, retryCount interface{}, lastError interface{}, nextRetryAt interface{}) *OutboxRepository_MarkRetryScheduled_Call {
	return &OutboxRepository_MarkRetryScheduled_Call{Call: _e.mock.On("MarkRetryScheduled", ctx, id, retryCount, lastError, nextRetryAt)}
}

func (_c *OutboxRepository_MarkRetryScheduled_Call) Run(run func(ctx context.Context, id uuid.UUID, retryCount int, lastError string, nextRetryAt time.Time)) *OutboxRepository_MarkRetryScheduled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *OutboxRepository_MarkRetryScheduled_Call) Return(err error) *OutboxRepository_MarkRetryScheduled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OutboxRepository_MarkRetryScheduled_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, retryCount int, lastError string, nextRetryAt time.Time) error) *OutboxRepository_MarkRetryScheduled_Call {
	_c.Call.Return(run)
	return _c
}
