// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"portal-system/internal/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewPermissionRepository creates a new instance of PermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mock expectations.
// The first argument is typically a *testing.T value.
func NewPermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionRepository {
	mock := &PermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PermissionRepository is an autogenerated mock type for the PermissionRepository type
type PermissionRepository struct {
	mock.Mock
}

type PermissionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PermissionRepository) EXPECT() *PermissionRepository_Expecter {
	return &PermissionRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type PermissionRepository
func (_mock *PermissionRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.Permission, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Permission, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Permission); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PermissionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type PermissionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PermissionRepository_Expecter) FindByID(ctx interface{}, id interface{}) *PermissionRepository_FindByID_Call {
	return &PermissionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *PermissionRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PermissionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PermissionRepository_FindByID_Call) Return(permission *model.Permission, err error) *PermissionRepository_FindByID_Call {
	_c.Call.Return(permission, err)
	return _c
}

func (_c *PermissionRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.Permission, error)) *PermissionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type PermissionRepository
func (_mock *PermissionRepository) List(ctx context.Context) ([]model.Permission, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Permission, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Permission); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PermissionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PermissionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PermissionRepository_Expecter) List(ctx interface{}) *PermissionRepository_List_Call {
	return &PermissionRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *PermissionRepository_List_Call) Run(run func(ctx context.Context)) *PermissionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PermissionRepository_List_Call) Return(permissions []model.Permission, err error) *PermissionRepository_List_Call {
	_c.Call.Return(permissions, err)
	return _c
}

func (_c *PermissionRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]model.Permission, error)) *PermissionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
