// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"portal-system/internal/domain"
	"portal-system/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewRoleService creates a new instance of RoleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleService {
	mock := &RoleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RoleService is an autogenerated mock type for the RoleService type
type RoleService struct {
	mock.Mock
}

type RoleService_Expecter struct {
	mock *mock.Mock
}

func (_m *RoleService) EXPECT() *RoleService_Expecter {
	return &RoleService_Expecter{mock: &_m.Mock}
}

// AssignPermission provides a mock function for the type RoleService
func (_mock *RoleService) AssignPermission(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, roleID uuid.UUID, permID uuid.UUID) error {
	ret := _mock.Called(ctx, meta, actor, roleID, permID)

	if len(ret) == 0 {
		panic("no return value specified for AssignPermission")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, meta, actor, roleID, permID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RoleService_AssignPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignPermission'
type RoleService_AssignPermission_Call struct {
	*mock.Call
}

// AssignPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - actor *domain.AuditUser
//   - roleID uuid.UUID
//   - permID uuid.UUID
func (_e *RoleService_Expecter) AssignPermission(ctx interface{}, meta interface{}, actor interface{}, roleID interface{}, permID interface{}) *RoleService_AssignPermission_Call {
	return &RoleService_AssignPermission_Call{Call: _e.mock.On("AssignPermission", ctx, meta, actor, roleID, permID)}
}

func (_c *RoleService_AssignPermission_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, roleID uuid.UUID, permID uuid.UUID)) *RoleService_AssignPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 *domain.AuditUser
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditUser)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *RoleService_AssignPermission_Call) Return(err error) *RoleService_AssignPermission_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RoleService_AssignPermission_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, roleID uuid.UUID, permID uuid.UUID) error) *RoleService_AssignPermission_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function for the type RoleService
func (_mock *RoleService) CreateRole(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, in domain.CreateRoleInput) (*models.Role, error) {
	ret := _mock.Called(ctx, meta, actor, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 *models.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, domain.CreateRoleInput) (*models.Role, error)); ok {
		return returnFunc(ctx, meta, actor, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, domain.CreateRoleInput) *models.Role); ok {
		r0 = returnFunc(ctx, meta, actor, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, domain.CreateRoleInput) error); ok {
		r1 = returnFunc(ctx, meta, actor, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleService_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type RoleService_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - actor *domain.AuditUser
//   - in domain.CreateRoleInput
func (_e *RoleService_Expecter) CreateRole(ctx interface{}, meta interface{}, actor interface{}, in interface{}) *RoleService_CreateRole_Call {
	return &RoleService_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, meta, actor, in)}
}

func (_c *RoleService_CreateRole_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, in domain.CreateRoleInput)) *RoleService_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 *domain.AuditUser
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditUser)
		}
		var arg3 domain.CreateRoleInput
		if args[3] != nil {
			arg3 = args[3].(domain.CreateRoleInput)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RoleService_CreateRole_Call) Return(role *models.Role, err error) *RoleService_CreateRole_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *RoleService_CreateRole_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, in domain.CreateRoleInput) (*models.Role, error)) *RoleService_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRole provides a mock function for the type RoleService
func (_mock *RoleService) DeleteRole(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, roleID uuid.UUID, replaceRoleID *uuid.UUID) error {
	ret := _mock.Called(ctx, meta, actor, roleID, replaceRoleID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID, *uuid.UUID) error); ok {
		r0 = returnFunc(ctx, meta, actor, roleID, replaceRoleID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RoleService_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type RoleService_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - actor *domain.AuditUser
//   - roleID uuid.UUID
//   - replaceRoleID *uuid.UUID
func (_e *RoleService_Expecter) DeleteRole(ctx interface{}, meta interface{}, actor interface{}, roleID interface{}, replaceRoleID interface{}) *RoleService_DeleteRole_Call {
	return &RoleService_DeleteRole_Call{Call: _e.mock.On("DeleteRole", ctx, meta, actor, roleID, replaceRoleID)}
}

func (_c *RoleService_DeleteRole_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, roleID uuid.UUID, replaceRoleID *uuid.UUID)) *RoleService_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 *domain.AuditUser
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditUser)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 *uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *RoleService_DeleteRole_Call) Return(err error) *RoleService_DeleteRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RoleService_DeleteRole_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, roleID uuid.UUID, replaceRoleID *uuid.UUID) error) *RoleService_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoles provides a mock function for the type RoleService
func (_mock *RoleService) ListRoles(ctx context.Context) ([]models.Role, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRoles")
	}

	var r0 []models.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Role, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Role); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleService_ListRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoles'
type RoleService_ListRoles_Call struct {
	*mock.Call
}

// ListRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RoleService_Expecter) ListRoles(ctx interface{}) *RoleService_ListRoles_Call {
	return &RoleService_ListRoles_Call{Call: _e.mock.On("ListRoles", ctx)}
}

func (_c *RoleService_ListRoles_Call) Run(run func(ctx context.Context)) *RoleService_ListRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RoleService_ListRoles_Call) Return(roles []models.Role, err error) *RoleService_ListRoles_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *RoleService_ListRoles_Call) RunAndReturn(run func(ctx context.Context) ([]models.Role, error)) *RoleService_ListRoles_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePermission provides a mock function for the type RoleService
func (_mock *RoleService) RemovePermission(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, roleID uuid.UUID, permID uuid.UUID) error {
	ret := _mock.Called(ctx, meta, actor, roleID, permID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePermission")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, meta, actor, roleID, permID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RoleService_RemovePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePermission'
type RoleService_RemovePermission_Call struct {
	*mock.Call
}

// RemovePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - actor *domain.AuditUser
//   - roleID uuid.UUID
//   - permID uuid.UUID
func (_e *RoleService_Expecter) RemovePermission(ctx interface{}, meta interface{}, actor interface{}, roleID interface{}, permID interface{}) *RoleService_RemovePermission_Call {
	return &RoleService_RemovePermission_Call{Call: _e.mock.On("RemovePermission", ctx, meta, actor, roleID, permID)}
}

func (_c *RoleService_RemovePermission_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, roleID uuid.UUID, permID uuid.UUID)) *RoleService_RemovePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 *domain.AuditUser
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditUser)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *RoleService_RemovePermission_Call) Return(err error) *RoleService_RemovePermission_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RoleService_RemovePermission_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, roleID uuid.UUID, permID uuid.UUID) error) *RoleService_RemovePermission_Call {
	_c.Call.Return(run)
	return _c
}
