// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicesmocks

import (
	"context"
	"portal-system/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewPermissionService creates a new instance of PermissionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionService {
	mock := &PermissionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PermissionService is an autogenerated mock type for the PermissionService type
type PermissionService struct {
	mock.Mock
}

type PermissionService_Expecter struct {
	mock *mock.Mock
}

func (_m *PermissionService) EXPECT() *PermissionService_Expecter {
	return &PermissionService_Expecter{mock: &_m.Mock}
}

// ListPermission provides a mock function for the type PermissionService
func (_mock *PermissionService) ListPermission(ctx context.Context) ([]models.Permission, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPermission")
	}

	var r0 []models.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Permission, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Permission); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PermissionService_ListPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPermission'
type PermissionService_ListPermission_Call struct {
	*mock.Call
}

// ListPermission is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PermissionService_Expecter) ListPermission(ctx interface{}) *PermissionService_ListPermission_Call {
	return &PermissionService_ListPermission_Call{Call: _e.mock.On("ListPermission", ctx)}
}

func (_c *PermissionService_ListPermission_Call) Run(run func(ctx context.Context)) *PermissionService_ListPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PermissionService_ListPermission_Call) Return(permissions []models.Permission, err error) *PermissionService_ListPermission_Call {
	_c.Call.Return(permissions, err)
	return _c
}

func (_c *PermissionService_ListPermission_Call) RunAndReturn(run func(ctx context.Context) ([]models.Permission, error)) *PermissionService_ListPermission_Call {
	_c.Call.Return(run)
	return _c
}
